myapp/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic import RedirectView


urlpatterns = [
    path('regex_app/', include('regex_app.urls')),
    path("admin/", admin.site.urls),
    path('', RedirectView.as_view(url='/regex_app/')),
]

regex_app/urls.py
from django.urls import path

from . import views

app_name="regex_app"
urlpatterns = [

    path('', views.index, name='index'),
    path('confirm/', views.confirm, name='confirm')
]

regex_app/models.py
from django.db import models

# Create your models here.

regex_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
import re



def index(request):

    return render(request,"regex_app/index.html")

def confirm(request):
    name=request.POST.get("name")
    age = request.POST.get("age")
    zip_code=request.POST.get("zip_code")
    tel=request.POST.get("tel")
    checkname=re.sub("\s","",name)
    checkage=re.match("^[0-9]{1,3}$",age)
    checkzip_code=re.match("(^[0-9]{3}-?[0-9]{4}$)",zip_code)
    checktel=re.match("(^[0-9]{3}-?[0-9]{4}-?[0-9]{4}$)",tel)
    if checkage and checkzip_code and checktel is not None:
        context = {
           "name":checkname,
           "age": checkage.group(),
           "zip_code":checkzip_code.group(),
           "tel":checktel.group(),
        }
        return render(request,"regex_app/confirm.html", context)  
    elif checkage and checkzip_code is not None:
            tel=""
            context = {
                "name":checkname,
                "age":age,
                "zip_code":zip_code,
                "tel":"",
            }
            return render(request,"regex_app/index.html",context)
    elif  checkage and checktel is not None:
            zip_code=""
            context={
                "name":checkname,
                "age":age,
                "zip_code":"",
                "tel":tel,
            }
            return render(request,"regex_app/index.html",context)
    elif checkzip_code and checktel is not None:
            age=""
            context={
                "name":checkname,
                "age":"",
                "zip_code":zip_code,
                "tel":tel,
            }
            return render(request,"regex_app/index.html",context)
    elif  checkage is not None:
            zip_code = ""
            tel=""
            context = {
                "name":checkname,
                "age":age,
                "zip_code":"",
                "tel":"",
            }
            return render(request,"regex_app/index.html",context)
    elif checkzip_code is not None:
            age=""
            tel=""
            context = {
                "name":checkname,
                "age":"",
                "zip_code":zip_code,
                "tel":"",
            }
            return render(request,"regex_app/index.html",context)
    elif  checktel is not None:
            age=""
            zip_code=""
            context = {
                "name":checkname,
                "age":"",
                "zip_code":"",
                "tel":tel,
            }
            return render(request,"regex_app/index.html",context)
    else:    
            context={
                "name":checkname,
                "age":"",
                "zip_code":"",
                "tel":"",
            } 
            return render(request,"regex_app/index.html",context)
        
        
       

regex_app/templates/regex_app/confirm.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>正規表現練習</title>
</head>

<body>
    <h1>確認してね</h1>
    <p>{{name}}</p>
    <p>{{age}}</p>
    <p>{{zip_code}}</p>
    <p>{{tel}}</p>

</body>

</html>

regex_app/templates/regex_app/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>正規表現練習</title>
</head>

<body>
    <h1>登録してね</h1>
    <form action="{% url 'regex_app:confirm' %}" method="POST">
        {% csrf_token %}
        <p>
            <label for="name">Name:
                <input type="text" name="name" id="name" value="{{ name }}">
            </label>
        </p>
        <p style="color: red;">
            {% if age == "" %}
            Ageは1~3桁の半角数字のみ入力してください。
            {% endif %}
        </p>
        <p>
            <label for="age">Age:
                <input type="text" name="age" id="age" value="{{age}}">
            </label>
        </p>
        <p style="color: red;">
            {% if zip_code == "" %}
            Zip codeは全7桁の半角数字のみ入力してください。(ハイフンはあってもなくてもOK)
            {% endif %}
        </p>
        <p>
            <label for="zip_code">Zip code:
                <input type="text" name="zip_code" id="zip_code" value="{{zip_code}}">
            </label>
        </p>
        <p style="color: red;">
            {% if tel == "" %}
            Cell phoneは全9桁の半角数字のみ入力してください。(ハイフンはあってもなくてもOK)
            {% endif %}
        </p>
        <p>
            <label for="tel">Cell phone:
                <input type="text" name="tel" id="tel" value="{{tel}}">
            </label>
        </p>
        <button type="submit">登録</button>
    </form>

</body>

</html>